# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'res/window.ui'
#
# Created: Mon Apr 22 20:22:36 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName(_fromUtf8("main_window"))
        main_window.resize(1123, 718)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/avatar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_window.setWindowIcon(icon)
        self.root_widget = QtGui.QWidget(main_window)
        self.root_widget.setObjectName(_fromUtf8("root_widget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.root_widget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.login_panel = QtGui.QWidget(self.root_widget)
        self.login_panel.setMinimumSize(QtCore.QSize(300, 700))
        self.login_panel.setMaximumSize(QtCore.QSize(300, 700))
        self.login_panel.setObjectName(_fromUtf8("login_panel"))
        self.loginarea = QtGui.QWidget(self.login_panel)
        self.loginarea.setGeometry(QtCore.QRect(20, 340, 271, 321))
        self.loginarea.setObjectName(_fromUtf8("loginarea"))
        self.login_btn = QtGui.QPushButton(self.loginarea)
        self.login_btn.setGeometry(QtCore.QRect(80, 260, 102, 41))
        self.login_btn.setMouseTracking(True)
        self.login_btn.setStyleSheet(_fromUtf8(""))
        self.login_btn.setObjectName(_fromUtf8("login_btn"))
        self.layoutWidget = QtGui.QWidget(self.loginarea)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 20, 165, 96))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.login_input_qq = QtGui.QLineEdit(self.layoutWidget)
        self.login_input_qq.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.login_input_qq.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.login_input_qq.setMaxLength(10)
        self.login_input_qq.setObjectName(_fromUtf8("login_input_qq"))
        self.verticalLayout.addWidget(self.login_input_qq)
        self.login_input_pwd = QtGui.QLineEdit(self.layoutWidget)
        self.login_input_pwd.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.login_input_pwd.setMaxLength(20)
        self.login_input_pwd.setEchoMode(QtGui.QLineEdit.Password)
        self.login_input_pwd.setObjectName(_fromUtf8("login_input_pwd"))
        self.verticalLayout.addWidget(self.login_input_pwd)
        self.label_2 = QtGui.QLabel(self.loginarea)
        self.label_2.setGeometry(QtCore.QRect(50, 206, 70, 18))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.loginarea)
        self.label.setGeometry(QtCore.QRect(50, 166, 70, 18))
        self.label.setObjectName(_fromUtf8("label"))
        self.remember_pwd = QtGui.QToolButton(self.loginarea)
        self.remember_pwd.setGeometry(QtCore.QRect(149, 159, 30, 26))
        self.remember_pwd.setFocusPolicy(QtCore.Qt.NoFocus)
        self.remember_pwd.setCheckable(True)
        self.remember_pwd.setChecked(True)
        self.remember_pwd.setObjectName(_fromUtf8("remember_pwd"))
        self.auto_login = QtGui.QToolButton(self.loginarea)
        self.auto_login.setGeometry(QtCore.QRect(149, 200, 30, 26))
        self.auto_login.setFocusPolicy(QtCore.Qt.NoFocus)
        self.auto_login.setCheckable(True)
        self.auto_login.setChecked(True)
        self.auto_login.setObjectName(_fromUtf8("auto_login"))
        self.login_invisable = QtGui.QToolButton(self.loginarea)
        self.login_invisable.setGeometry(QtCore.QRect(149, 123, 30, 26))
        self.login_invisable.setFocusPolicy(QtCore.Qt.NoFocus)
        self.login_invisable.setCheckable(True)
        self.login_invisable.setChecked(False)
        self.login_invisable.setObjectName(_fromUtf8("login_invisable"))
        self.label_5 = QtGui.QLabel(self.loginarea)
        self.label_5.setGeometry(QtCore.QRect(50, 130, 70, 18))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.login_loading_area = QtGui.QWidget(self.login_panel)
        self.login_loading_area.setGeometry(QtCore.QRect(20, 340, 271, 321))
        self.login_loading_area.setObjectName(_fromUtf8("login_loading_area"))
        self.login_loading_btn = QtGui.QPushButton(self.login_loading_area)
        self.login_loading_btn.setGeometry(QtCore.QRect(20, 260, 102, 41))
        self.login_loading_btn.setMouseTracking(True)
        self.login_loading_btn.setStyleSheet(_fromUtf8(""))
        self.login_loading_btn.setObjectName(_fromUtf8("login_loading_btn"))
        self.login_loading_label = QtGui.QLabel(self.login_loading_area)
        self.login_loading_label.setGeometry(QtCore.QRect(100, 230, 70, 18))
        self.login_loading_label.setObjectName(_fromUtf8("login_loading_label"))
        self.login_vcimg = QtGui.QLabel(self.login_loading_area)
        self.login_vcimg.setGeometry(QtCore.QRect(70, 40, 171, 81))
        self.login_vcimg.setObjectName(_fromUtf8("login_vcimg"))
        self.login_input_vc = QtGui.QLineEdit(self.login_loading_area)
        self.login_input_vc.setGeometry(QtCore.QRect(50, 150, 161, 28))
        self.login_input_vc.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhUppercaseOnly)
        self.login_input_vc.setMaxLength(5)
        self.login_input_vc.setObjectName(_fromUtf8("login_input_vc"))
        self.login_loading_login_btn = QtGui.QPushButton(self.login_loading_area)
        self.login_loading_login_btn.setGeometry(QtCore.QRect(150, 260, 102, 41))
        self.login_loading_login_btn.setMouseTracking(True)
        self.login_loading_login_btn.setStyleSheet(_fromUtf8(""))
        self.login_loading_login_btn.setObjectName(_fromUtf8("login_loading_login_btn"))
        self.close_btn_login = QtGui.QToolButton(self.login_panel)
        self.close_btn_login.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.close_btn_login.setFocusPolicy(QtCore.Qt.NoFocus)
        self.close_btn_login.setObjectName(_fromUtf8("close_btn_login"))
        self.gridLayout_2.addWidget(self.login_panel, 0, 0, 1, 1)
        self.main_widget = QtGui.QSplitter(self.root_widget)
        self.main_widget.setFrameShape(QtGui.QFrame.Panel)
        self.main_widget.setFrameShadow(QtGui.QFrame.Plain)
        self.main_widget.setOrientation(QtCore.Qt.Horizontal)
        self.main_widget.setObjectName(_fromUtf8("main_widget"))
        self.main_panel = QtGui.QWidget(self.main_widget)
        self.main_panel.setMinimumSize(QtCore.QSize(300, 0))
        self.main_panel.setMaximumSize(QtCore.QSize(300, 16777215))
        self.main_panel.setObjectName(_fromUtf8("main_panel"))
        self.layoutWidget1 = QtGui.QWidget(self.main_panel)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 107, 33))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.close_btn = QtGui.QToolButton(self.layoutWidget1)
        self.close_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.close_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.close_btn.setObjectName(_fromUtf8("close_btn"))
        self.horizontalLayout.addWidget(self.close_btn)
        self.min_btn = QtGui.QToolButton(self.layoutWidget1)
        self.min_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.min_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.min_btn.setObjectName(_fromUtf8("min_btn"))
        self.horizontalLayout.addWidget(self.min_btn)
        self.max_btn = QtGui.QToolButton(self.layoutWidget1)
        self.max_btn.setMinimumSize(QtCore.QSize(31, 31))
        self.max_btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.max_btn.setObjectName(_fromUtf8("max_btn"))
        self.horizontalLayout.addWidget(self.max_btn)
        self.avatar = QtGui.QLabel(self.main_panel)
        self.avatar.setGeometry(QtCore.QRect(10, 30, 40, 40))
        self.avatar.setMinimumSize(QtCore.QSize(40, 40))
        self.avatar.setMaximumSize(QtCore.QSize(40, 40))
        self.avatar.setObjectName(_fromUtf8("avatar"))
        self.nick = QtGui.QLabel(self.main_panel)
        self.nick.setGeometry(QtCore.QRect(60, 43, 261, 18))
        self.nick.setObjectName(_fromUtf8("nick"))
        self.search_input = QtGui.QLineEdit(self.main_panel)
        self.search_input.setGeometry(QtCore.QRect(0, 100, 300, 28))
        self.search_input.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhUppercaseOnly)
        self.search_input.setObjectName(_fromUtf8("search_input"))
        self.tab_widget = QtGui.QTabWidget(self.main_panel)
        self.tab_widget.setGeometry(QtCore.QRect(0, 130, 300, 570))
        self.tab_widget.setMinimumSize(QtCore.QSize(300, 570))
        self.tab_widget.setMaximumSize(QtCore.QSize(300, 570))
        self.tab_widget.setObjectName(_fromUtf8("tab_widget"))
        self.tab_friend = QtGui.QWidget()
        self.tab_friend.setObjectName(_fromUtf8("tab_friend"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_friend)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.friends_list_tree = QtGui.QTreeWidget(self.tab_friend)
        self.friends_list_tree.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.friends_list_tree.setAlternatingRowColors(True)
        self.friends_list_tree.setObjectName(_fromUtf8("friends_list_tree"))
        self.friends_list_tree.headerItem().setText(0, _fromUtf8("1"))
        self.friends_list_tree.header().setVisible(False)
        self.gridLayout_5.addWidget(self.friends_list_tree, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_friend, _fromUtf8(""))
        self.tab_group = QtGui.QWidget()
        self.tab_group.setObjectName(_fromUtf8("tab_group"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_group)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.listWidget = QtGui.QListWidget(self.tab_group)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_9.addWidget(self.listWidget, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_group, _fromUtf8(""))
        self.tab_session = QtGui.QWidget()
        self.tab_session.setObjectName(_fromUtf8("tab_session"))
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_session)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.session_list_widget = QtGui.QListWidget(self.tab_session)
        self.session_list_widget.setAlternatingRowColors(True)
        self.session_list_widget.setObjectName(_fromUtf8("session_list_widget"))
        self.gridLayout_6.addWidget(self.session_list_widget, 0, 0, 1, 1)
        self.tab_widget.addTab(self.tab_session, _fromUtf8(""))
        self.toggle_btn = QtGui.QToolButton(self.main_panel)
        self.toggle_btn.setGeometry(QtCore.QRect(270, 0, 31, 31))
        self.toggle_btn.setText(_fromUtf8(""))
        self.toggle_btn.setCheckable(True)
        self.toggle_btn.setObjectName(_fromUtf8("toggle_btn"))
        self.content_panel = QtGui.QWidget(self.main_widget)
        self.content_panel.setObjectName(_fromUtf8("content_panel"))
        self.gridLayout = QtGui.QGridLayout(self.content_panel)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.center_splitter = QtGui.QSplitter(self.content_panel)
        self.center_splitter.setOrientation(QtCore.Qt.Vertical)
        self.center_splitter.setHandleWidth(2)
        self.center_splitter.setObjectName(_fromUtf8("center_splitter"))
        self.body = QtGui.QWidget(self.center_splitter)
        self.body.setObjectName(_fromUtf8("body"))
        self.gridLayout_4 = QtGui.QGridLayout(self.body)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.dlg_header_widget = QtGui.QWidget(self.body)
        self.dlg_header_widget.setMinimumSize(QtCore.QSize(0, 50))
        self.dlg_header_widget.setObjectName(_fromUtf8("dlg_header_widget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.dlg_header_widget)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.friend_name_label = QtGui.QLabel(self.dlg_header_widget)
        self.friend_name_label.setObjectName(_fromUtf8("friend_name_label"))
        self.verticalLayout_2.addWidget(self.friend_name_label)
        self.flnick_label = QtGui.QLabel(self.dlg_header_widget)
        self.flnick_label.setObjectName(_fromUtf8("flnick_label"))
        self.verticalLayout_2.addWidget(self.flnick_label)
        self.gridLayout_7.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(226, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(188, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_4.addWidget(self.dlg_header_widget, 0, 0, 1, 1)
        self.web_view = QtWebKit.QWebView(self.body)
        self.web_view.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.web_view.setObjectName(_fromUtf8("web_view"))
        self.gridLayout_4.addWidget(self.web_view, 1, 0, 1, 1)
        self.background_view = QtWebKit.QWebView(self.body)
        self.background_view.setMaximumSize(QtCore.QSize(0, 0))
        self.background_view.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.background_view.setObjectName(_fromUtf8("background_view"))
        self.gridLayout_4.addWidget(self.background_view, 2, 0, 1, 1)
        self.footer = QtGui.QWidget(self.center_splitter)
        self.footer.setObjectName(_fromUtf8("footer"))
        self.gridLayout_3 = QtGui.QGridLayout(self.footer)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem2 = QtGui.QSpacerItem(308, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.send_btn = QtGui.QPushButton(self.footer)
        self.send_btn.setObjectName(_fromUtf8("send_btn"))
        self.horizontalLayout_2.addWidget(self.send_btn)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.input_div = QtWebKit.QWebView(self.footer)
        self.input_div.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.input_div.setObjectName(_fromUtf8("input_div"))
        self.gridLayout_3.addWidget(self.input_div, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.center_splitter, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.main_widget, 0, 1, 1, 1)
        main_window.setCentralWidget(self.root_widget)

        self.retranslateUi(main_window)
        self.tab_widget.setCurrentIndex(0)
        QtCore.QObject.connect(self.close_btn_login, QtCore.SIGNAL(_fromUtf8("clicked()")), main_window.close)
        QtCore.QObject.connect(self.close_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), main_window.close)
        QtCore.QObject.connect(self.login_input_qq, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.login_btn.click)
        QtCore.QObject.connect(self.login_input_pwd, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.login_btn.click)
        QtCore.QObject.connect(self.login_input_vc, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.login_loading_login_btn.click)
        QtCore.QMetaObject.connectSlotsByName(main_window)
        main_window.setTabOrder(self.login_input_qq, self.login_input_pwd)
        main_window.setTabOrder(self.login_input_pwd, self.login_btn)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "COCO QQ", None, QtGui.QApplication.UnicodeUTF8))
        self.login_btn.setText(QtGui.QApplication.translate("main_window", "登录", None, QtGui.QApplication.UnicodeUTF8))
        self.login_input_qq.setText(QtGui.QApplication.translate("main_window", "1234567", None, QtGui.QApplication.UnicodeUTF8))
        self.login_input_qq.setPlaceholderText(QtGui.QApplication.translate("main_window", "账号", None, QtGui.QApplication.UnicodeUTF8))
        self.login_input_pwd.setText(QtGui.QApplication.translate("main_window", "1234567", None, QtGui.QApplication.UnicodeUTF8))
        self.login_input_pwd.setPlaceholderText(QtGui.QApplication.translate("main_window", "密码", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("main_window", "自动登录", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("main_window", "记住密码", None, QtGui.QApplication.UnicodeUTF8))
        self.remember_pwd.setText(QtGui.QApplication.translate("main_window", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.auto_login.setText(QtGui.QApplication.translate("main_window", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.login_invisable.setText(QtGui.QApplication.translate("main_window", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("main_window", "隐身登录", None, QtGui.QApplication.UnicodeUTF8))
        self.login_loading_btn.setText(QtGui.QApplication.translate("main_window", "返回", None, QtGui.QApplication.UnicodeUTF8))
        self.login_loading_label.setText(QtGui.QApplication.translate("main_window", "登录中...", None, QtGui.QApplication.UnicodeUTF8))
        self.login_vcimg.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.login_input_vc.setPlaceholderText(QtGui.QApplication.translate("main_window", "请输入验证码", None, QtGui.QApplication.UnicodeUTF8))
        self.login_loading_login_btn.setText(QtGui.QApplication.translate("main_window", "登录", None, QtGui.QApplication.UnicodeUTF8))
        self.avatar.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.nick.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.search_input.setPlaceholderText(QtGui.QApplication.translate("main_window", "搜索好友", None, QtGui.QApplication.UnicodeUTF8))
        self.friends_list_tree.setSortingEnabled(False)
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_friend), QtGui.QApplication.translate("main_window", "好友", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_group), QtGui.QApplication.translate("main_window", "群组", None, QtGui.QApplication.UnicodeUTF8))
        self.tab_widget.setTabText(self.tab_widget.indexOf(self.tab_session), QtGui.QApplication.translate("main_window", "会话", None, QtGui.QApplication.UnicodeUTF8))
        self.friend_name_label.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.flnick_label.setText(QtGui.QApplication.translate("main_window", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.send_btn.setText(QtGui.QApplication.translate("main_window", "发送[Ctrl/Shift+Enter]", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import rsrc_rc
